version: "3"
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-0:
    image: wurstmeister/kafka
    container_name: kafka-0
    ports:
      - "9092:9092"
      - "29092:29092"
      - "39092:39092"
    environment:
      - KAFKA_BROKER_ID= 0
      - KAFKA_LISTENERS= INTERNAL://:9092,EXTERNAL_SAME_HOST://:29092,EXTERNAL_DIFFERENT_HOST://:39092
      - KAFKA_ADVERTISED_LISTENERS= INTERNAL://kafka-0:9092,EXTERNAL_SAME_HOST://localhost:29092,EXTERNAL_DIFFERENT_HOST://192.168.20.143:39092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME= INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENERS= yes
      - JMX_PORT=9999
      - javaagent:/home/centos/jmx_prometheus_javaagent-0.16.1.jar=7071:/home/cenots/kafka.yml
    depends_on:
      - zookeeper

  kafka-1:
    image: wurstmeister/kafka
    container_name: kafka-1
    ports:
      - "9093:9093"
      - "29093:29093"
      - "39093:39093"

    environment:
      - KAFKA_BROKER_ID= 1
      - KAFKA_LISTENERS= INTERNAL://:9093,EXTERNAL_SAME_HOST://:29093,EXTERNAL_DIFFERENT_HOST://:39093
      - KAFKA_ADVERTISED_LISTENERS= INTERNAL://kafka-1:9093,EXTERNAL_SAME_HOST://localhost:29093,EXTERNAL_DIFFERENT_HOST://192.168.20.143:39093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME= INTERNAL
            - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENERS= yes
      - javaagent:/home/centos/jmx_prometheus_javaagent-0.16.1.jar=9090:/home/cenots/kafka.yml
    depends_on:
      - zookeeper

  kafka-2:
    image: wurstmeister/kafka
    container_name: kafka-2
    ports:
      - "9094:9094"
      - "29094:29094"
      - "39094:39094"

    environment:
      - KAFKA_BROKER_ID= 2
      - KAFKA_LISTENERS= INTERNAL://:9094,EXTERNAL_SAME_HOST://:29094,EXTERNAL_DIFFERENT_HOST://:39094
      - KAFKA_ADVERTISED_LISTENERS= INTERNAL://kafka-2:9094,EXTERNAL_SAME_HOST://localhost:29094,EXTERNAL_DIFFERENT_HOST://192.168.20.143:39094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME= INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENERS= yes
      - javaagent:/home/centos/jmx_prometheus_javaagent-0.16.1.jar=9090:/home/cenots/kafka.yml
    depends_on:
      - zookeeper

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
     - --path.procfs=/host/proc
     - --path.sysfs=/host/sys
     - --collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    user: "root"

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager
    restart: always
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
      KAFKA_MANAGER_AUTH_ENABLED: "false"
      KAFKA_MANAGER_JMX_ENABLED: "true"
      KAFKA_MANAGER_JMX_TYPE: "jmx"
      KAFKA_MANAGER_JMX_LOWER_CASE_OUTPUT_NAME: "true"
      KAFKA_MANAGER_JMX_URL: "service:jmx:rmi:///jndi/rmi:///192.168.20.143:9999/jmxrmi"
      KAFKA_MANAGER_JMX_USERNAME: ""
      KAFKA_MANAGER_JMX_PASSWORD: ""
      KAFKA_MANAGER_JMX_PUSHGATEWAY_JOB: "pushgateway"
      KAFKA_MANAGER_JMX_PUSHGATEWAY_ADDRESS: "pushgateway:9091"
    command: -Dpidfile.path=/dev/null

  kafka_exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    ports:
      - "7071:7071"
    environment:
      KAFKA_SERVERS: "172.19.0.10:9092,172.19.0.7:9093,172.19.0.4:9094"
volumes:
  grafana-data:
  kafka_manager_data:
  prometheus:
